version: '3.8'
services:
  checkout:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: checkout_db
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: root
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8002:8000
    depends_on:
      - checkout_db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    environment:
      DB_HOST: checkout_db
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - checkout_db

  checkout_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33069:3306
