###

# curl 'http://localhost:8004/api/user'
#  -H 'Connection: keep-alive'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWYzMDFmZTA4Yzc2YzE4YTQ1ZGNiNzQ3YTIyNTE0MGYzNTQyOTY1NTAzOTE1ZmNkOWFiYTViZTBiZjkxNDJjYjdkYmIyNmUwNzJiYjRhZmUiLCJpYXQiOjE2MDA0NDQwODYsIm5iZiI6MTYwMDQ0NDA4NiwiZXhwIjoxNjMxOTgwMDg2LCJzdWIiOiIyMSIsInNjb3BlcyI6WyJhZG1pbiJdfQ.bwGpiFE-y5Jb6L22AR0xUaTzNAw3lV8qT0qOTiOJelCLdWlQb4UfGMDhR2G0JZX0g-3oJ8jhHu_-qalxNl5Jv2shPMjMpdFk-0KLK3Ps0xagx664O3ASxta6y06WYpYroN_aJbrzzgDesjumlts-qsPYf8yKpzojRiMGU0r7kRd1kilKESPd76XJhxMLaQmOi49NBLOAGKVfyYwrmIVwOYCWTG6JUquyUxK9LbF2uCjqM9pB7D7SdguFmz60LJr9B5z6PrucCUZsiSgoqNBgkM6oSCIIvQbnUVDTJ9VodXmgDuvURDhy4XVXlMdGkVXH6fkxkryMUCGNiMFeOhXjVFFh-K5W9zbiYNmVBhiGiiWKUQSy8FfmPBqIB-X3IUj34ecMWZ3MOxM-P1ovgVhsh8Y4GVTtruWswsWu-UNj9Kigp69uImoSYlEDFCRvysZjwMloCFpea2pdPbj6nKaHut9ue5T2Dk8jolh5YumfF8zH-KsBT6WTkvH2d7YPYhlbOTrt-QZqjHQiryQaEaq3-KvfhBHEakMqTwMjswgm0p4jp-LiyrLDSdE8QGMLj1LckQpK3sAmnU8aqRRO6kQ0fSek1gjzRrYCvnzmMhwmF3qIUJHQeLWeCO470NXpPKkm_Fi5T5KcYWS4sGXXcSyVu3Qi4SAIa21dc6CgBm2x8AQ'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'
#  -H 'Origin: http://localhost:4200'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Referer: http://localhost:4200/dashboard'
#  -H 'Accept-Language: en-US,en;q=0.9,sq;q=0.8,de;q=0.7'
#  --compressed
GET http://localhost:8004/api/user
Connection: keep-alive
Accept: application/json, text/plain, */*
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWYzMDFmZTA4Yzc2YzE4YTQ1ZGNiNzQ3YTIyNTE0MGYzNTQyOTY1NTAzOTE1ZmNkOWFiYTViZTBiZjkxNDJjYjdkYmIyNmUwNzJiYjRhZmUiLCJpYXQiOjE2MDA0NDQwODYsIm5iZiI6MTYwMDQ0NDA4NiwiZXhwIjoxNjMxOTgwMDg2LCJzdWIiOiIyMSIsInNjb3BlcyI6WyJhZG1pbiJdfQ.bwGpiFE-y5Jb6L22AR0xUaTzNAw3lV8qT0qOTiOJelCLdWlQb4UfGMDhR2G0JZX0g-3oJ8jhHu_-qalxNl5Jv2shPMjMpdFk-0KLK3Ps0xagx664O3ASxta6y06WYpYroN_aJbrzzgDesjumlts-qsPYf8yKpzojRiMGU0r7kRd1kilKESPd76XJhxMLaQmOi49NBLOAGKVfyYwrmIVwOYCWTG6JUquyUxK9LbF2uCjqM9pB7D7SdguFmz60LJr9B5z6PrucCUZsiSgoqNBgkM6oSCIIvQbnUVDTJ9VodXmgDuvURDhy4XVXlMdGkVXH6fkxkryMUCGNiMFeOhXjVFFh-K5W9zbiYNmVBhiGiiWKUQSy8FfmPBqIB-X3IUj34ecMWZ3MOxM-P1ovgVhsh8Y4GVTtruWswsWu-UNj9Kigp69uImoSYlEDFCRvysZjwMloCFpea2pdPbj6nKaHut9ue5T2Dk8jolh5YumfF8zH-KsBT6WTkvH2d7YPYhlbOTrt-QZqjHQiryQaEaq3-KvfhBHEakMqTwMjswgm0p4jp-LiyrLDSdE8QGMLj1LckQpK3sAmnU8aqRRO6kQ0fSek1gjzRrYCvnzmMhwmF3qIUJHQeLWeCO470NXpPKkm_Fi5T5KcYWS4sGXXcSyVu3Qi4SAIa21dc6CgBm2x8AQ
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Origin: http://localhost:4200
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:4200/dashboard
Accept-Language: en-US,en;q=0.9,sq;q=0.8,de;q=0.7

###

