version: '3.8'
services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: users_db
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - users_db

  users_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33068:3306
