version: '3.8'
services:
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: emails
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_HOST: docker.for.mac.localhost
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: emails
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33067:3306
